### ISSUE TITLE
Support ECC ciphers

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/bifravst#202]
Using ECC ciphers provides [50-100 times signing operations](http://ww1.microchip.com/downloads/en/DeviceDoc/00003442A.pdf), and [AWS supports it](https://aws.amazon.com/blogs/iot/elliptic-curve-cryptography-and-forward-secrecy-support-in-aws-iot-3/) so Bifravst should switch to this.

In addition it also allows the device to create it's own keys, however this increases complexity during manufacturing and onboarding so I think this is not very relevant for the Bifravst use-case.

There might be no change for the firmware, the modem already supports ECC ciphers for TLS.

The same AT command `AT%CMNG` is used to provision these certs.

- [x] Use ECC ciphers in AWS flavour of Bifravst 
- [x] Use ECC ciphers in Azure flavour of Bifravst
- [x] Use ECC ciphers in Firmware
- [ ] Limit used TLS ciphers: https://github.com/bifravst/firmware/issues/235

**Comment by coderbyheart** [comment]
I just tried it, and it works just like that. The only thing I needed to change was the key generation, everything else is unchanged.
No changes to the device firmware, or AWS backend required.

**Comment by savvyintegrations** [comment]
Have you tried ECC certs with the new AWS IoT SDK v2 client, specifically the pub/sub sample at https://github.com/aws/aws-iot-device-sdk-js-v2/tree/main/samples/node/pub_sub? In my experience the sample works with RSA certs, but not with ECC. With the latter I get "Unable to build TLS context" (use of `openssl s_client -connect $MQTT_ENDPOINT:8443 -CAfile $AMAZON_ROOT_CA_PATH -cert $DEVICE_CERT_PATH -key $DEVICE_KEY_PATH` indicates there's no problem with the TLS context and the handshake proceeds).

I was forced to do some R&D with the new MQTT client b/c I want do to the following to support ULP provisioning (avoid JITP), but it results in a cert with `certificateMode` set to `SNI_ONLY` instead of `DEFAULT` (for certs registered via JITP), and the v1 SDK does not support `SNI_ONLY`:
```
aws iot register-certificate-without-ca --status ACTIVE --certificate-pem file:///path/to/certs/$DEVICE_ID.crt.pem
aws iot attach-thing-principal --thing-name $DEVICE_ID --principal $CERT_ARN
```
Anyway, I was just wondering whether you had run into ECC issues with the v2 SDK client. I'm contemplating opening an issue in that project but it would be very involved.

**Comment by coderbyheart** [comment]
I found the v2 IoT Client SDK to be painfully to work with (see https://github.com/bifravst/aws/issues/181) ... v1 is a convenience wrapper around MQTT.js and provides all the features needed right now in Bifravst (websockets in the app, and device simulator in the CLI). Since there are not features missing in v1, I have put the migration on hold.

That's why I haven't tried ECC with v2, yet.

**Comment by coderbyheart** [comment]
I've decided to close this now, since https://github.com/bifravst/firmware/issues/235 is an improvement. In general Bifravst is using ECC now.

**Comment by coderbyheart** [comment]
> it results in a cert with `certificateMode` set to `SNI_ONLY` instead of `DEFAULT` (for certs registered via JITP), and the v1 SDK does not support `SNI_ONLY`

This really sounds like a bug/missing feature in v2 SDK because [SNI has been added as a requirement for AWS IoT](https://docs.aws.amazon.com/iot/latest/developerguide/transport-security.html).

Looking [at the v1 Changelog](https://github.com/aws/aws-iot-device-sdk-js/blob/abc9fa4137b0d93455ed996a77e1d684a16dcdd0/CHANGELOG.md), they are sending the SNI string since 2.2.7, so I wonder why that does not work.

> send SNI string while connecting to AWS IoT

**Comment by savvyintegrations** [comment]
I'm glad you said something more, because it led to the discovery that although v1@2.2.7 was *released*, it wasn't published to NPM. So when you just do `npm i aws-iot-device-sdk` you get v2.2.6 which is the last version *without* SNI support. 

I decided to add `servername` to the client config [per their commit](https://github.com/aws/aws-iot-device-sdk-js/commit/abc9fa4137b0d93455ed996a77e1d684a16dcdd0) and voila! ECC-based certs known to AWS via `register-certificate-wtihout-ca` (i.e., `SNI_ONLY` certs) now work with the v1 SDK and our [device-simulator-v2](https://github.com/nRFCloud/device-simulator-v2) (my changes to the sim will be published soon).
